# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md
  - link.md
footer: 'follow us on <a href="https://twitter.com/0xcnTeam">twitter</a>'

style: dark  # dark (default) or light or hacker
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
markdown: kramdown
redcarpet:
  extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]